[package]
name = "counter"
version = "0.1.0"
edition = "2021"

[dependencies]
arm = { git = "https://github.com/anoma/arm-risc0.git", features = ["logic_circuit"], tag = "v0.2.0", default-features = false }
serde = { version = "1.0.197", default-features = false }
